// 节点导航
export default {
    最热节点: [
        { title: '问与答', value: 'qna' },
        { title: '酷工作', value: 'jobs' },
        { title: '程序员', value: 'programmer' },
        { title: '分享发现', value: 'share' },
        { title: 'macOS', value: 'macos' },
        { title: 'Apple', value: 'apple' },
        { title: '分享创造', value: 'create' },
        { title: 'Python', value: 'python' },
        { title: '职场话题', value: 'career' },
        { title: '宽带症候群', value: 'bb' },
        { title: 'Android', value: 'android' },
        { title: 'iPhone', value: 'iphone' },
        { title: '全球工单系统', value: 'gts' },
        { title: 'MacBook Pro', value: 'mbp' },
        { title: '求职', value: 'cv' }
    ],
    分享与探索: [
        { title: '问与答', value: 'qna' },
        { title: '分享发现', value: 'share' },
        { title: '分享创造', value: 'create' },
        { title: '奇思妙想', value: 'ideas' },
        { title: '分享邀请码', value: 'in' },
        { title: '自言自语', value: 'autistic' },
        { title: '设计', value: 'design' },
        { title: 'Blog', value: 'blog' }
    ],
    V2EX: [
        { title: 'V2EX', value: 'v2ex' },
        { title: '反馈', value: 'feedback' },
        { title: 'Project Babel', value: 'babel' },
        { title: '使用指南', value: 'guide' }
    ],
    Apple: [
        { title: 'macOS', value: 'macos' },
        { title: 'Apple', value: 'apple' },
        { title: 'iPhone', value: 'iphone' },
        { title: 'MacBook Pro', value: 'mbp' },
        { title: 'iOS', value: 'ios' },
        { title: 'iPad', value: 'ipad' },
        { title: 'MacBook', value: 'macbook' },
        { title: ' WATCH', value: 'watch' },
        { title: '配件', value: 'accessory' },
        { title: 'MacBook Air', value: 'mba' },
        { title: 'iMac', value: 'imac' },
        { title: 'Mac mini', value: 'macmini' },
        { title: 'Xcode', value: 'xcode' },
        { title: 'Mac Pro', value: 'macpro' },
        { title: 'WWDC', value: 'wwdc' },
        { title: 'iPod', value: 'ipod' },
        { title: 'AirPods', value: 'airpods' },
        { title: 'MobileMe', value: 'mobileme' },
        { title: 'iWork', value: 'iwork' },
        { title: 'iLife', value: 'ilife' },
        { title: 'GarageBand', value: 'garageband' },
        { title: 'HomeKit', value: 'homekit' }
    ],
    前端开发: [
        { title: '微信', value: 'wechat' },
        { title: 'Chrome', value: 'chrome' },
        { title: 'Vue.js', value: 'vue' },
        { title: 'CSS', value: 'css' },
        { title: '浏览器', value: 'browsers' },
        { title: 'React', value: 'react' },
        { title: 'Firefox', value: 'firefox' },
        { title: 'Flutter', value: 'flutter' },
        { title: 'Angular', value: 'angular' },
        { title: 'Edge', value: 'edge' },
        { title: 'Electron', value: 'electron' },
        { title: 'Web Dev', value: 'webdev' },
        { title: 'Ionic', value: 'ionic' },
        { title: 'Next.js', value: 'nextjs' },
        { title: 'Nuxt.js', value: 'nuxtjs' },
        { title: 'Vite', value: 'vite' }
    ],
    编程语言: [
        { title: 'Python', value: 'python' },
        { title: 'Java', value: 'java' },
        { title: 'PHP', value: 'php' },
        { title: 'JavaScript', value: 'js' },
        { title: 'Node.js', value: 'nodejs' },
        { title: 'Go 编程语言', value: 'go' },
        { title: 'HTML', value: 'html' },
        { title: 'Swift', value: 'swift' },
        { title: '.NET', value: 'dotnet' },
        { title: 'Ruby on Rails', value: 'ror' },
        { title: 'Rust', value: 'rust' },
        { title: 'C#', value: 'csharp' },
        { title: 'Ruby', value: 'ruby' },
        { title: 'TypeScript', value: 'typescript' },
        { title: 'Kotlin', value: 'kotlin' },
        { title: 'Lua', value: 'lua' }
    ],
    后端架构: [
        { title: '云计算', value: 'cloud' },
        { title: '服务器', value: 'server' },
        { title: 'DNS', value: 'dns' },
        { title: 'MySQL', value: 'mysql' },
        { title: 'NGINX', value: 'nginx' },
        { title: 'Docker', value: 'docker' },
        { title: '数据库', value: 'db' },
        { title: 'Django', value: 'django' },
        { title: 'MongoDB', value: 'mongodb' },
        { title: 'Redis', value: 'redis' },
        { title: 'DevOps', value: 'devops' },
        { title: 'Kubernetes', value: 'k8s' },
        { title: 'Tornado', value: 'tornado' },
        { title: 'Elasticsearch', value: 'elasticsearch' },
        { title: 'API', value: 'api' },
        { title: 'LeanCloud', value: 'leancloud' },
        { title: 'Cloudflare', value: 'cloudflare' },
        { title: 'Timescale', value: 'timescale' }
    ],
    机器学习: [
        { title: '机器学习', value: 'ml' },
        { title: '数学', value: 'math' },
        { title: 'TensorFlow', value: 'tensorflow' },
        { title: '自然语言处理', value: 'nlp' },
        { title: 'CUDA', value: 'cuda' },
        { title: 'Torch', value: 'torch' },
        { title: 'Core ML', value: 'coreml' },
        { title: 'Keras', value: 'keras' }
    ],
    iOS: [
        { title: 'iDev', value: 'idev' },
        { title: 'iCode', value: 'icode' },
        { title: 'iMarketing', value: 'imarketing' },
        { title: 'iAd', value: 'iad' },
        { title: 'iTransfer', value: 'itransfer' }
    ],
    Geek: [
        { title: '程序员', value: 'programmer' },
        { title: '宽带症候群', value: 'bb' },
        { title: 'Android', value: 'android' },
        { title: 'Linux', value: 'linux' },
        { title: '外包', value: 'outsourcing' },
        { title: '硬件', value: 'hardware' },
        { title: 'Bitcoin', value: 'bitcoin' },
        { title: '站长', value: 'webmaster' },
        { title: '汽车', value: 'car' },
        { title: '路由器', value: 'router' },
        { title: '编程', value: 'programming' },
        { title: 'Linode', value: 'linode' },
        { title: '设计师', value: 'designer' },
        { title: 'Markdown', value: 'markdown' },
        { title: 'Visual Studio Code', value: 'vscode' },
        { title: 'Kindle', value: 'kindle' },
        { title: '游戏开发', value: 'gamedev' },
        { title: 'Minecraft', value: 'minecraft' },
        { title: '字体排印', value: 'typography' },
        { title: 'Atom', value: 'atom' },
        { title: '商业模式', value: 'business' },
        { title: 'SONY', value: 'sony' },
        { title: 'LeetCode', value: 'leetcode' },
        { title: 'Photoshop', value: 'photoshop' },
        { title: 'Serverless', value: 'serverless' },
        { title: 'Amazon', value: 'amazon' },
        { title: 'LEGO', value: 'lego' },
        { title: 'GitLab', value: 'gitlab' },
        { title: '电动汽车', value: 'ev' },
        { title: 'RSS', value: 'rss' },
        { title: 'DJI', value: 'dji' },
        { title: 'GitHub Copilot', value: 'copilot' },
        { title: '奇绩创坛', value: 'miracleplus' }
    ],
    游戏: [
        { title: '游戏', value: 'games' },
        { title: 'Steam', value: 'steam' },
        { title: 'Nintendo Switch', value: 'switch' },
        { title: '英雄联盟', value: 'lol' },
        { title: 'PlayStation 4', value: 'ps4' },
        { title: 'iGame', value: 'igame' },
        { title: 'StarCraft 2', value: 'sc2' },
        { title: 'Battlefield 3', value: 'bf3' },
        { title: 'World of Warcraft', value: 'wow' },
        { title: '王者荣耀', value: '5v5' },
        { title: '怀旧游戏', value: 'retro' },
        { title: 'EVE', value: 'eve' },
        { title: '精灵宝可梦', value: 'pokemon' },
        { title: 'PlayStation 5', value: 'ps5' },
        { title: '3DS', value: '3ds' },
        { title: 'Gran Turismo', value: 'gt' },
        { title: 'Battlefield 4', value: 'bf4' },
        { title: 'Wii U', value: 'wiiu' },
        { title: 'Battlefield V', value: 'bfv' },
        { title: 'GameDB', value: 'gamedb' }
    ],
    生活: [
        { title: '二手交易', value: 'all4all' },
        { title: '酷工作', value: 'jobs' },
        { title: '职场话题', value: 'career' },
        { title: '求职', value: 'cv' },
        { title: '天黑以后', value: 'afterdark' },
        { title: '免费赠送', value: 'free' },
        { title: '音乐', value: 'music' },
        { title: '电影', value: 'movie' },
        { title: '物物交换', value: 'exchange' },
        { title: '投资', value: 'invest' },
        { title: '团购', value: 'tuan' },
        { title: '剧集', value: 'tv' },
        { title: '旅行', value: 'travel' },
        { title: '信用卡', value: 'creditcard' },
        { title: '美酒与美食', value: 'taste' },
        { title: '阅读', value: 'reading' },
        { title: '摄影', value: 'photograph' },
        { title: '宠物', value: 'pet' },
        { title: 'Baby', value: 'baby' },
        { title: '绿茵场', value: 'soccer' },
        { title: '咖啡', value: 'coffee' },
        { title: '日记', value: 'diary' },
        { title: '非诚勿扰', value: 'love' },
        { title: '骑行', value: 'bike' },
        { title: '植物', value: 'plant' },
        { title: '蘑菇', value: 'mushroom' },
        { title: '行程控', value: 'mileage' }
    ],
    Internet: [
        { title: 'Google', value: 'google' },
        { title: 'YouTube', value: 'youtube' },
        { title: 'Notion', value: 'notion' },
        { title: 'Reddit', value: 'reddit' }
    ],
    城市: [
        { title: '北京', value: 'beijing' },
        { title: '上海', value: 'shanghai' },
        { title: '深圳', value: 'shenzhen' },
        { title: '杭州', value: 'hangzhou' },
        { title: '成都', value: 'chengdu' },
        { title: '广州', value: 'guangzhou' },
        { title: '武汉', value: 'wuhan' },
        { title: '南京', value: 'nanjing' },
        { title: '西安', value: 'xian' },
        { title: '昆明', value: 'kunming' },
        { title: '重庆', value: 'chongqing' },
        { title: '苏州', value: 'suzhou' },
        { title: '厦门', value: 'xiamen' },
        { title: '天津', value: 'tianjin' },
        { title: '青岛', value: 'qingdao' },
        { title: 'San Francisco', value: 'sanfrancisco' },
        { title: 'New York', value: 'nyc' },
        { title: 'Los Angeles', value: 'la' },
        { title: '东京', value: 'tokyo' },
        { title: '贵阳', value: 'guiyang' },
        { title: 'Singapore', value: 'singapore' },
        { title: 'Boston', value: 'boston' }
    ]
};
